name: Go CI

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  ci:
    name: Go CI Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Run tests
        run: go test ./... -v

      - name: Build
        if: github.event_name == 'release'
        run: go build -o userfc .

      - name: Upload artifact
        if: github.event_name == 'release'
        uses: actions/upload-artifact@v4
        with:
          name: userfc-${{ github.ref_name }}
          path: userfc
